=== hackingscience/roboband/RoboBandBackend/resources/ugendefs.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!-- 
	DTD for a list of available ugens
	lastmod : 04-sep-05
-->

<!ENTITY audio "gaga">
<!ENTITY control "gogo">

<!ELEMENT ugendefs (ugen*)>
<!ELEMENT ugen (arg*,outputs?,special*)>
<!ATTLIST ugen
		  class		CDATA		#REQUIRED
		  rates		NMTOKENS	#REQUIRED
		  range		(unipolar|bipolar)	#IMPLIED
>
<!ELEMENT arg EMPTY>
<!ATTLIST arg
		  name		CDATA		#REQUIRED
		  def		CDATA 		#IMPLIED
		  type		(number|array)	#IMPLIED
>
<!ELEMENT outputs EMPTY>
<!ATTLIST outputs
		  type		(fixed|arg|arraySize)	#IMPLIED
		  val		CDATA		#IMPLIED
		  mul		CDATA		#IMPLIED
>
<!ELEMENT special EMPTY>
<!ATTLIST special
		  idx		CDATA		#REQUIRED
		  name		CDATA 		#REQUIRED
>

=== hackingscience/roboband/RoboBandBackend/resources/ugendefs.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE ugendefs SYSTEM "http://www.sciss.de/jcollider/ugendefs.dtd">
<!-- last mod: 19-sep-09 sciss -->
<ugendefs>
	<ugen class="PitchShift" rates="audio">
		<arg name="in" def="0.0" />
		<arg name="windowSize" def="0.2" />
		<arg name="pitchRatio" def="1.0" />
		<arg name="pitchDispersion" def="0.0" />
		<arg name="timeDispersion" def="0.0" />
	</ugen>
	
	<ugen class="PSinGrain" rates="audio">
		<arg name="freq" def="440.0" />
		<arg name="dur" def="0.2" />
		<arg name="amp" def="1.0" />
	</ugen>

	<ugen class="BufChannels" rates="control scalar">
		<arg name="bufnum" />
	</ugen>
	
	<ugen class="BufDur" rates="control scalar">
		<arg name="bufnum" />
	</ugen>
	
	<ugen class="BufSamples" rates="control scalar">
		<arg name="bufnum" />
	</ugen>

	<ugen class="BufFrames" rates="control scalar">
		<arg name="bufnum" />
	</ugen>
	
	<ugen class="BufRateScale" rates="control scalar">
		<arg name="bufnum" />
	</ugen>
	
	<ugen class="BufSampleRate" rates="control scalar">
		<arg name="bufnum" />
	</ugen>

	<ugen class="NumRunningSynths" rates="control scalar" />

	<ugen class="NumBuffers" rates="scalar" />

	<ugen class="NumControlBuses" rates="scalar" />

	<ugen class="NumAudioBuses" rates="scalar" />

	<ugen class="NumInputBuses" rates="scalar" />

	<ugen class="NumOutputBuses" rates="scalar" />

	<ugen class="SubsampleOffset" rates="scalar" />

	<ugen class="ControlRate" rates="scalar" />

	<ugen class="ControlDur" rates="scalar" />

	<ugen class="RadiansPerSample" rates="scalar" />

	<ugen class="SampleDur" rates="scalar" />

	<ugen class="SampleRate" rates="scalar" />
 	
	<ugen class="MulAdd" rates="audio control">
		<arg name="in" />
		<arg name="mul" def="1.0" />
		<arg name="add" def="0.0" />
	</ugen>
	
	<ugen class="BinaryOpUGen" rates="audio control demand scalar">
		<arg name="a" />
		<arg name="b" />
		<special idx="0" name="+" />
		<special idx="1" name="-" />
		<special idx="2" name="*" />
		<special idx="3" name="div" />
		<special idx="4" name="/" />
		<special idx="5" name="mod" />
		<special idx="6" name="==" />
		<special idx="7" name="!=" />
		<special idx="8" name="&lt;" />
		<special idx="9" name="&gt;" />
		<special idx="10" name="&lt;=" />
		<special idx="11" name="&gt;=" />
		<special idx="12" name="min" />
		<special idx="13" name="max" />
		<special idx="14" name="&amp;" />
		<special idx="15" name="|" />
		<special idx="16" name="^" />
		<special idx="17" name="lcm" />
		<special idx="18" name="gcd" />
		<special idx="19" name="round" />
		<special idx="20" name="roundUp" />
		<special idx="21" name="trunc" />
		<special idx="22" name="atan2" />
		<special idx="23" name="hypot" />
		<special idx="24" name="hypotApx" />
		<special idx="25" name="pow" />
		<special idx="26" name="leftShift" />
		<special idx="27" name="rightShift" />
		<special idx="28" name="unsignedRightShift" />
		<special idx="29" name="fill" />
		<special idx="30" name="ring1" />
		<special idx="31" name="ring2" />
		<special idx="32" name="ring3" />
		<special idx="33" name="ring4" />
		<special idx="34" name="difsqr" />
		<special idx="35" name="sumsqr" />
		<special idx="36" name="sqrsum" />
		<special idx="37" name="sqrdif" />
		<special idx="38" name="absdif" />
		<special idx="39" name="thresh" />
		<special idx="40" name="amclip" />
		<special idx="41" name="scaleneg" />
		<special idx="42" name="clip2" />
		<special idx="43" name="excess" />
		<special idx="44" name="fold2" />
		<special idx="45" name="wrap2" />
		<special idx="46" name="firstArg" />
		<special idx="47" name="rrand" />
		<special idx="48" name="exprand" />
	</ugen>

	<ugen class="UnaryOpUGen" rates="audio control demand scalar">
		<arg name="a" />
		<special idx="0" name="neg" />
		<special idx="1" name="not" />
		<special idx="2" name="isNil" />
		<special idx="3" name="notNil" />
		<special idx="4" name="bitNot" />
		<special idx="5" name="abs" />
		<special idx="6" name="asFloat" />
		<special idx="7" name="asInteger" />
		<special idx="8" name="ceil" />
		<special idx="9" name="floor" />
		<special idx="10" name="frac" />
		<special idx="11" name="sign" />
		<special idx="12" name="squared" />
		<special idx="13" name="cubed" />
		<special idx="14" name="sqrt" />
		<special idx="15" name="exp" />
		<special idx="16" name="reciprocal" />
		<special idx="17" name="midicps" />
		<special idx="18" name="cpsmidi" />
		<special idx="19" name="midiratio" />
		<special idx="20" name="ratiomidi" />
		<special idx="21" name="dbamp" />
		<special idx="22" name="ampdb" />
		<special idx="23" name="octcps" />
		<special idx="24" name="cpsoct" />
		<special idx="25" name="log" />
		<special idx="26" name="log2" />
		<special idx="27" name="log10" />
		<special idx="28" name="sin" />
		<special idx="29" name="cos" />
		<special idx="30" name="tan" />
		<special idx="31" name="asin" />
		<special idx="32" name="acos" />
		<special idx="33" name="atan" />
		<special idx="34" name="sinh" />
		<special idx="35" name="cosh" />
		<special idx="36" name="tanh" />
		<special idx="37" name="rand" />
		<special idx="38" name="rand2" />
		<special idx="39" name="linrand" />
		<special idx="40" name="bilinrand" />
		<special idx="41" name="sum3rand" />
		<special idx="42" name="distort" />
		<special idx="43" name="softclip" />
		<special idx="44" name="coin" />
		<special idx="45" name="digitValue" />
		<special idx="46" name="silence" />
		<special idx="47" name="thru" />
		<special idx="48" name="rectWindow" />
		<special idx="49" name="hanWindow" />
		<special idx="50" name="welWindow" />
		<special idx="51" name="triWindow" />
		<special idx="52" name="ramp" />
		<special idx="53" name="scurve" />
	</ugen>

	<ugen class="TBall" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="g" def="10" />
		<arg name="damp" def="0" />
		<arg name="friction" def="0.01" />
	</ugen>
	
	<ugen class="Ball" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="g" def="10" />
		<arg name="damp" def="0" />
		<arg name="friction" def="0.01" />
	</ugen>
	
	<ugen class="Spring" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="spring" def="0" />
		<arg name="damp" def="0" />
	</ugen>

	<ugen class="DetectSilence" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="amp" def="0.0001" />
		<arg name="time" def="0.1" />
		<arg name="doneAction" def="0" />
<!--	<outputs type="fixed" val="0" /> -->
	</ugen>
	
	<ugen class="BLowPass" rates="audio">
		<arg name="in" />
		<arg name="freq" def="1200.0" />
		<arg name="rq" def="1.0" />
	</ugen>
	
	<ugen class="BHiPass" rates="audio">
		<arg name="in" />
		<arg name="freq" def="1200.0" />
		<arg name="rq" def="1.0" />
	</ugen>
	
	<ugen class="BAllPass" rates="audio">
		<arg name="in" />
		<arg name="freq" def="1200.0" />
		<arg name="rq" def="1.0" />
	</ugen>
	
	<ugen class="BBandPass" rates="audio">
		<arg name="in" />
		<arg name="freq" def="1200.0" />
		<arg name="bw" def="1.0" />
	</ugen>
	
	<ugen class="BBandStop" rates="audio">
		<arg name="in" />
		<arg name="freq" def="1200.0" />
		<arg name="bw" def="1.0" />
	</ugen>
	
	<ugen class="BPeakEQ" rates="audio">
		<arg name="in" />
		<arg name="freq" def="1200.0" />
		<arg name="rq" def="1.0" />
		<arg name="db" def="0.0" />
	</ugen>
	
	<ugen class="BLowShelf" rates="audio">
		<arg name="in" />
		<arg name="freq" def="1200.0" />
		<arg name="rs" def="1.0" />
		<arg name="db" def="0.0" />
	</ugen>
	
	<ugen class="BHiShelf" rates="audio">
		<arg name="in" />
		<arg name="freq" def="1200.0" />
		<arg name="rs" def="1.0" />
		<arg name="db" def="0.0" />
	</ugen>
	
	<ugen class="Formlet" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="freq" def="440.0" />
		<arg name="attacktime" def="1.0" />
		<arg name="decaytime" def="1.0" />
	</ugen>

	<ugen class="Ringz" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="freq" def="440.0" />
		<arg name="decaytime" def="1.0" />
	</ugen>

	<ugen class="SOS" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="a0" def="0.0" />
		<arg name="a1" def="0.0" />
		<arg name="a2" def="0.0" />
		<arg name="b1" def="0.0" />
		<arg name="b2" def="0.0" />
	</ugen>

	<ugen class="FOS" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="a0" def="0.0" />
		<arg name="a1" def="0.0" />
		<arg name="b1" def="0.0" />
	</ugen>

	<ugen class="Slew" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="up" def="1.0" />
		<arg name="dn" def="1.0" />
	</ugen>

	<ugen class="Median" rates="audio control">
		<arg name="length" def="3" />
		<arg name="in" def="0.0" />
	</ugen>

	<ugen class="LPZ2" rates="audio control">
		<arg name="in" def="0.0" />
	</ugen>

	<ugen class="BRZ2" rates="audio control">
		<arg name="in" def="0.0" />
	</ugen>

	<ugen class="BPZ2" rates="audio control">
		<arg name="in" def="0.0" />
	</ugen>

	<ugen class="HPZ2" rates="audio control">
		<arg name="in" def="0.0" />
	</ugen>

	<ugen class="Slope" rates="audio control">
		<arg name="in" def="0.0" />
	</ugen>

	<ugen class="LPZ1" rates="audio control">
		<arg name="in" def="0.0" />
	</ugen>

	<ugen class="HPZ1" rates="audio control">
		<arg name="in" def="0.0" />
	</ugen>

	<ugen class="MidEQ" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="freq" def="440.0" />
		<arg name="rq" def="1.0" />
		<arg name="db" def="0.0" />
	</ugen>

	<ugen class="BPF" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="freq" def="440.0" />
		<arg name="rq" def="1.0" />
	</ugen>

	<ugen class="BRF" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="freq" def="440.0" />
		<arg name="rq" def="1.0" />
	</ugen>

	<ugen class="LPF" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="freq" def="440.0" />
	</ugen>

	<ugen class="HPF" rates="audio control">
		<arg name="in" def="0.0" />
		<arg name="freq" def="440.0" />
	</ugen>

	<ugen class="RLPF" rates="audio control">
		<arg name="in" def="0.0" />
